APP_NAME="mini-RAG"
APP_VERSION="0.1"

FILE_ALLOWED_TYPES=["text/plain", "application/pdf"]
FILE_MAX_SIZE=10  # 10 MB
FILE_DEFAULT_CHUNK_SIZE=512000 # 512KB

POSTGRES_USERNAME=""
POSTGRES_PASSWORD=""
POSTGRES_HOST="pgvector" 
POSTGRES_PORT=5432  
POSTGRES_MAIN_DATABASE="minirag"

# ========================= LLM Config =========================
GENERATION_BACKEND = "OPENAI"
EMBEDDING_BACKEND = "OPENAI"

OPENAI_API_KEY="sk-proj--"
OPENAI_API_URL=
COHERE_API_KEY="as-as-sa"

GENERATION_MODEL_ID_LITERAL=["gpt-4o-mini", "gpt-3.5-turbo"]
GENERATION_MODEL_ID="gpt-4o-mini"
EMBEDDING_MODEL_ID="text-embedding-3-small"
EMBEDDING_MODEL_SIZE=1536

INPUT_DAFAULT_MAX_CHARACTERS=1024
GENERATION_DAFAULT_MAX_TOKENS=200
GENERATION_DAFAULT_TEMPERATURE=0.1

# ========================= Vector DB Config =========================
VECTOR_DB_BACKEND_LITERAL=["QDRANT", "PGVECTOR"]
VECTOR_DB_BACKEND="PGVECTOR"
VECTOR_DB_PATH="qdrant_db_new"
VECTOR_DB_DISTANCE_METHOD="cosine"
VECTOR_DB_PGVEC_INDEX_THRESHOLD = 300

# ========================= Template Configs =========================
PRIMARY_LANG = "en"
DEFAULT_LANG = "en" 